### ISSUE TITLE
How to run the target code on single GPU

### ISSUE THREAD

**Issue by Claydon-Wang** [DianCh/AdaContrast#2]
Hi, Thanks for the great work. I try to run the code on single GPU. I have used 
`export CUDA_VISIBLE_DEVICES=0`

The code run well when training on source dataset, but I still get the error on target dataset. My log is shown as below:

`Error executing job with overrides: ['seed=2020', 'port=10001', 'memo=target', 'project=VISDA-C', 'data.data_root=/home/clayton/Project/TTA/AdaContrast/datasets', 'data.workers=8', 'data.dataset=VISDA-C', 'data.source_domains=[train]', 'data.target_domains=[validation]', 'model_src.arch=resnet18', 'model_tta.src_log_dir=/home/clayton/Project/TTA/AdaContrast/output/VISDA-C/source/', 'optim.lr=2e-4']
Traceback (most recent call last):
  File "main_adacontrast.py", line 46, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main_adacontrast.py", line 142, in main_worker
    train_target_adacontrast(args)
  File "/home/clayton/Project/TTA/AdaContrast/target.py", line 323, in train_target_domain
    train_epoch(train_loader, model, banks, optimizer, epoch, args)
  File "/home/clayton/Project/TTA/AdaContrast/target.py", line 371, in train_epoch
    _, logits_q, logits_ins, keys = model(images_q, images_k)
  File "/home/clayton/anaconda3/envs/dassl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/clayton/Project/TTA/AdaContrast/moco/builder.py", line 171, in forward
    im_k, idx_unshuffle = self._batch_shuffle_ddp(im_k)
  File "/home/clayton/anaconda3/envs/dassl/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/clayton/Project/TTA/AdaContrast/moco/builder.py", line 107, in _batch_shuffle_ddp
    x_gather = concat_all_gather(x)
  File "/home/clayton/anaconda3/envs/dassl/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/clayton/Project/TTA/AdaContrast/utils.py", line 106, in concat_all_gather
    tensors_gather = [torch.ones_like(tensor) for _ in range(dist.get_world_size())]
  File "/home/clayton/anaconda3/envs/dassl/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1067, in get_world_size
    return _get_group_size(group)
  File "/home/clayton/anaconda3/envs/dassl/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 453, in _get_group_size
    default_pg = _get_default_group()
  File "/home/clayton/anaconda3/envs/dassl/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 584, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.`

Do you have any suggestions for the problem? Thanks in advance.

**Comment by Claydon-Wang** [comment]
get it.
"concat_all_gather" is used in moco/builder.py, which only support multi GPU.
I just remove them and successfully run the target code
